<a href="https://colab.research.google.com/github/patrykbtm/data-science-bootcamp/blob/master/01_wprowadzenie/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Podstawy**


In [2]:
import numpy as np
np.__version__

'1.18.5'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

**1D Array**

[1 2 3 4 5]


In [14]:
x = np.array([1, 2, 3, 4, 5])
print(x)

print(type(x))

print("x.ndim: ", x.ndim)
print("x.shape: ", x.shape)
print("x.size: ", x.size)
print("x.dtype: ", x.dtype)

[1 2 3 4 5]
<class 'numpy.ndarray'>
x.ndim:  1
x.shape:  (5,)
x.size:  5
x.dtype:  int64


In [15]:
y = np.array([1.4, 2.3, 3.1])
print(y)

print(type(y))

print("y.ndim: ", y.ndim)
print("y.shape: ", y.shape)
print("y.size: ", y.size)
print("y.dtype: ", y.dtype)

[1.4 2.3 3.1]
<class 'numpy.ndarray'>
y.ndim:  1
y.shape:  (3,)
y.size:  3
y.dtype:  float64


**2D Array**

In [17]:
z = np.array([[1, 2], [-3, 1]])
print(z)

print(type(z))

print("z.ndim: ", z.ndim)
print("z.shape: ", z.shape)
print("z.size: ", z.size)
print("z.dtype: ", z.dtype)

[[ 1  2]
 [-3  1]]
<class 'numpy.ndarray'>
z.ndim:  2
z.shape:  (2, 2)
z.size:  4
z.dtype:  int64


**3D Array**

In [21]:
a3D =  np.array([
                 [[4,3,1],
                  [3,2,1]],
                 
                 [[4,3,2],
                  [5,3,1]],
                 
                 [[4,1,5],
                  [6,4,2]]
])

print(a3D)
print(a3D.ndim)
print(a3D.shape)

[[[4 3 1]
  [3 2 1]]

 [[4 3 2]
  [5 3 1]]

 [[4 1 5]
  [6 4 2]]]
3
(3, 2, 3)


**Tablice - Typy danych**

In [9]:
tabInt = np.array([2,4,5])
print(tabInt)
print(tabInt.dtype)

tabInt = np.array([1, 4.3, 5.7], dtype = 'int64')
print(tabInt)
print(tabInt.dtype)

tabFloat = np.array([1.4, 4,2])
print(tabFloat)
print(tabFloat.dtype)

[2 4 5]
int64
[1 4 5]
int64
[1.4 4.  2. ]
float64


**Tworzenie tablic**

In [10]:
tabZeros = np.zeros(shape = [4, 10])
print(tabZeros)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [11]:
tabOnes = np.ones(shape = [5,5], dtype = 'int64')
print(tabOnes)
print(tabOnes.dtype)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
int64


In [13]:
tabFull = np.full(shape = [3,3], fill_value= 5)
print(tabFull)
print(tabFull.dtype)

[[5 5 5]
 [5 5 5]
 [5 5 5]]
int64


In [15]:
tabArange10 = np.arange(10)
print(tabArange10)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
tabArange5_9 = np.arange(start = 5, stop = 10)
print(tabArange5_9)

[5 6 7 8 9]


In [17]:
tabArange10_90 = np.arange(start = 10, stop = 91, step = 10)
print(tabArange10_90)

[10 20 30 40 50 60 70 80 90]


In [18]:
tabArange100_20 = np.arange(start = 100, stop = 10, step = -10)
print(tabArange100_20)

[100  90  80  70  60  50  40  30  20]


In [19]:
tabLinspace0_1 = np.linspace(start = 0, stop = 1, num=11)
print(tabLinspace0_1)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [26]:
A = np.arange(15)
print(A)
print()
B = A.reshape((3, 5))
print(B)
print()
C = A.reshape((5, -1))
print(C)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


**Podstawowe operacje na tablicach**

In [27]:
A = np.array([3 , 1, 4, 2])
B = np.array([3, -1 ,3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [34]:
print("A + B: ", A + B)
print("A - B:", A - B)
print("A * B: ", A * B)
print("A / B:", A / B)
print("A + 3", A + 3)
print("A * 2", A * 2)

A + B:  [6 0 7 4]
A - B: [0 2 1 0]
A * B:  [ 9 -1 12  4]
A / B: [ 1.         -1.          1.33333333  1.        ]
A + 3 [6 4 7 5]
A * 2 [6 2 8 4]


In [36]:
print(np.add(A, B))
print(np.subtract(A, B))
print(np.multiply(A,B))
print(np.divide(A, B))

[6 0 7 4]
[0 2 1 0]
[ 9 -1 12  4]
[ 1.         -1.          1.33333333  1.        ]


In [6]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, -2]])

print("X\n",X)
print("Y\n",Y)

print("X * Y\n", np.dot(X, Y))
print("Y * X\n", Y.dot(X))

print("Lub\nY * X\n", Y @ X)

X
 [[ 1  3]
 [-2  0]]
Y
 [[ 6  0]
 [-1 -2]]
X * Y
 [[  3  -6]
 [-12   0]]
Y * X
 [[ 6 18]
 [ 3 -3]]
Lub
Y * X
 [[ 6 18]
 [ 3 -3]]


**Generowanie liczb pseudolosowych**


In [23]:
np.random.seed(0)
print("ROZKŁAD NORMALNY\n")
print(np.random.randn())
print("\n",np.random.randn(10))
print("\n",np.random.randn(10,4))

print("\nLosowanie z zakresu <0;1)")
print(np.random.rand(10,4))

print("\nLosowanie z zakresu <min;max)")
print(np.random.randint(low = 10, high=101, size = 10))

print("\nWybór losowego elemenu z listy")
print(np.random.choice([4,2,5,1,77,45,3,22]))
print(np.random.choice(['python', 'java', 'c#']))

print("\nTasowanie zbioru")
data = np.arange(10)
print(data)
np.random.shuffle(data)
print(data)

ROZKŁAD NORMALNY

1.764052345967664

 [ 0.40015721  0.97873798  2.2408932   1.86755799 -0.97727788  0.95008842
 -0.15135721 -0.10321885  0.4105985   0.14404357]

 [[ 1.45427351  0.76103773  0.12167502  0.44386323]
 [ 0.33367433  1.49407907 -0.20515826  0.3130677 ]
 [-0.85409574 -2.55298982  0.6536186   0.8644362 ]
 [-0.74216502  2.26975462 -1.45436567  0.04575852]
 [-0.18718385  1.53277921  1.46935877  0.15494743]
 [ 0.37816252 -0.88778575 -1.98079647 -0.34791215]
 [ 0.15634897  1.23029068  1.20237985 -0.38732682]
 [-0.30230275 -1.04855297 -1.42001794 -1.70627019]
 [ 1.9507754  -0.50965218 -0.4380743  -1.25279536]
 [ 0.77749036 -1.61389785 -0.21274028 -0.89546656]]

Losowanie z zakresu <0;1)
[[0.19658236 0.36872517 0.82099323 0.09710128]
 [0.83794491 0.09609841 0.97645947 0.4686512 ]
 [0.97676109 0.60484552 0.73926358 0.03918779]
 [0.28280696 0.12019656 0.2961402  0.11872772]
 [0.31798318 0.41426299 0.0641475  0.69247212]
 [0.56660145 0.26538949 0.52324805 0.09394051]
 [0.5759465  0.92

**Podstawowe funkcje dostepne w bibliotece NumPy**


In [27]:
print("Exp z 1:", np.exp(1))
print("Pierwiastek z 25: ", np.sqrt(25))

Exp z 1: 2.718281828459045
Pierwiastek z 25:  5.0


In [32]:
print(np.all([2,3,4]))
print(np.all([2,3,0]))

print(np.any([2,3,0]))
print(np.any([0,0,0]))


True
False
True
False


In [43]:
A = np.random.rand(5)
print(A)

print("Indeks max wartości: ", np.argmax(A))
print("Max wartość: ", A[np.argmax(A)])
print(A.max())

print("Indeks min wartości: ", np.argmin(A))
print("Min wartość: ", A[np.argmin(A)])
print(A.min())

print("Sortowanie indeksów wg wartości ", np.argsort(A))

print("Srednia elementów: ", np.mean(A))
print("Mediana:  ", np.median(A))
print("Odchylenie standardowe: ", np.std(A))

[0.33940382 0.48954894 0.33898512 0.17949026 0.1709866 ]
Indeks max wartości:  1
Max wartość:  0.4895489368910937
0.4895489368910937
Indeks min wartości:  4
Min wartość:  0.17098659868313149
0.17098659868313149
Sortowanie indeksów wg wartości  [4 3 2 0 1]
Srednia elementów:  0.3036829465442755
Mediana:   0.3389851167797783
Odchylenie standardowe:  0.11840653212626484


**Indeksowanie, wycinanie**

In [58]:
A = np.arange(20)
print(A)

print(A[2])
print(A[2:])
print(A[:2])
print(A[[0, 2]])
print(A[-1])
print(A[10:15])

A = A.reshape(4,-1)
print(A)

print("W1: ", A[0])
print("W2: ", A[1])

print("K2: ", A[:,1])
print("Element W2-K2: ", A[1,1])

print(A[1:3, 1:4])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
2
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0 1]
[0 2]
19
[10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
W1:  [0 1 2 3 4]
W2:  [5 6 7 8 9]
K2:  [ 1  6 11 16]
Element W2-K2:  6
[[ 6  7  8]
 [11 12 13]]


**Iteracja po tablicach**

In [64]:
RowANum = 1
for row in A:
  print("Wiersz", RowANum, ":", row)
  RowANum=RowANum+1

Wiersz 1 : [0 1 2 3 4]
Wiersz 2 : [5 6 7 8 9]
Wiersz 3 : [10 11 12 13 14]
Wiersz 4 : [15 16 17 18 19]


In [67]:
RowANum = 1
for row in A:
  print("Pierwsze 3 el z wiersza", RowANum, ":", row[:3])
  RowANum=RowANum+1

Pierwsze 3 el z wiersza 1 : [0 1 2]
Pierwsze 3 el z wiersza 2 : [5 6 7]
Pierwsze 3 el z wiersza 3 : [10 11 12]
Pierwsze 3 el z wiersza 4 : [15 16 17]


In [68]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


**Zmiana rozmiaru tablic**

In [72]:
print(A)
print(A.shape)
A = A.reshape(5,4)
print(A)
print(A.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
(5, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
(5, 4)


In [73]:
print(A.ravel()) #wypłaszczenie tablicy

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [75]:
print(A.T) #transponowanie tablicy

[[ 0  4  8 12 16]
 [ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]]


**Maski logiczne**

In [77]:
B = np.arange(start = -10, stop = 10, step = 0.5)
B = B.reshape(10, -1)
print(B)

[[-10.   -9.5  -9.   -8.5]
 [ -8.   -7.5  -7.   -6.5]
 [ -6.   -5.5  -5.   -4.5]
 [ -4.   -3.5  -3.   -2.5]
 [ -2.   -1.5  -1.   -0.5]
 [  0.    0.5   1.    1.5]
 [  2.    2.5   3.    3.5]
 [  4.    4.5   5.    5.5]
 [  6.    6.5   7.    7.5]
 [  8.    8.5   9.    9.5]]


In [78]:
print(B > 0)

[[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [79]:
print(B[B>0])

[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.
 9.5]


In [82]:
print(np.bitwise_and(B > -5, B < 5))

[[False False False False]
 [False False False False]
 [False False False  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True False False]
 [False False False False]
 [False False False False]]


In [84]:
print(B[np.bitwise_and(B > -5, B < 5)])

[-4.5 -4.  -3.5 -3.  -2.5 -2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5  2.
  2.5  3.   3.5  4.   4.5]
