<a href="https://colab.research.google.com/github/patrykbtm/data-science-bootcamp/blob/master/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Podstawy**


In [1]:
import numpy as np
np.__version__

'1.18.5'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

**1D Array**

[1 2 3 4 5]


In [14]:
x = np.array([1, 2, 3, 4, 5])
print(x)

print(type(x))

print("x.ndim: ", x.ndim)
print("x.shape: ", x.shape)
print("x.size: ", x.size)
print("x.dtype: ", x.dtype)

[1 2 3 4 5]
<class 'numpy.ndarray'>
x.ndim:  1
x.shape:  (5,)
x.size:  5
x.dtype:  int64


In [15]:
y = np.array([1.4, 2.3, 3.1])
print(y)

print(type(y))

print("y.ndim: ", y.ndim)
print("y.shape: ", y.shape)
print("y.size: ", y.size)
print("y.dtype: ", y.dtype)

[1.4 2.3 3.1]
<class 'numpy.ndarray'>
y.ndim:  1
y.shape:  (3,)
y.size:  3
y.dtype:  float64


**2D Array**

In [17]:
z = np.array([[1, 2], [-3, 1]])
print(z)

print(type(z))

print("z.ndim: ", z.ndim)
print("z.shape: ", z.shape)
print("z.size: ", z.size)
print("z.dtype: ", z.dtype)

[[ 1  2]
 [-3  1]]
<class 'numpy.ndarray'>
z.ndim:  2
z.shape:  (2, 2)
z.size:  4
z.dtype:  int64


**3D Array**

In [21]:
a3D =  np.array([
                 [[4,3,1],
                  [3,2,1]],
                 
                 [[4,3,2],
                  [5,3,1]],
                 
                 [[4,1,5],
                  [6,4,2]]
])

print(a3D)
print(a3D.ndim)
print(a3D.shape)

[[[4 3 1]
  [3 2 1]]

 [[4 3 2]
  [5 3 1]]

 [[4 1 5]
  [6 4 2]]]
3
(3, 2, 3)
