<a href="https://colab.research.google.com/github/patrykbtm/data-science-bootcamp/blob/master/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Podstawy**


In [2]:
import numpy as np
np.__version__

'1.18.5'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

**1D Array**

[1 2 3 4 5]


In [14]:
x = np.array([1, 2, 3, 4, 5])
print(x)

print(type(x))

print("x.ndim: ", x.ndim)
print("x.shape: ", x.shape)
print("x.size: ", x.size)
print("x.dtype: ", x.dtype)

[1 2 3 4 5]
<class 'numpy.ndarray'>
x.ndim:  1
x.shape:  (5,)
x.size:  5
x.dtype:  int64


In [15]:
y = np.array([1.4, 2.3, 3.1])
print(y)

print(type(y))

print("y.ndim: ", y.ndim)
print("y.shape: ", y.shape)
print("y.size: ", y.size)
print("y.dtype: ", y.dtype)

[1.4 2.3 3.1]
<class 'numpy.ndarray'>
y.ndim:  1
y.shape:  (3,)
y.size:  3
y.dtype:  float64


**2D Array**

In [17]:
z = np.array([[1, 2], [-3, 1]])
print(z)

print(type(z))

print("z.ndim: ", z.ndim)
print("z.shape: ", z.shape)
print("z.size: ", z.size)
print("z.dtype: ", z.dtype)

[[ 1  2]
 [-3  1]]
<class 'numpy.ndarray'>
z.ndim:  2
z.shape:  (2, 2)
z.size:  4
z.dtype:  int64


**3D Array**

In [21]:
a3D =  np.array([
                 [[4,3,1],
                  [3,2,1]],
                 
                 [[4,3,2],
                  [5,3,1]],
                 
                 [[4,1,5],
                  [6,4,2]]
])

print(a3D)
print(a3D.ndim)
print(a3D.shape)

[[[4 3 1]
  [3 2 1]]

 [[4 3 2]
  [5 3 1]]

 [[4 1 5]
  [6 4 2]]]
3
(3, 2, 3)


**Tablice - Typy danych**

In [9]:
tabInt = np.array([2,4,5])
print(tabInt)
print(tabInt.dtype)

tabInt = np.array([1, 4.3, 5.7], dtype = 'int64')
print(tabInt)
print(tabInt.dtype)

tabFloat = np.array([1.4, 4,2])
print(tabFloat)
print(tabFloat.dtype)

[2 4 5]
int64
[1 4 5]
int64
[1.4 4.  2. ]
float64


**Tworzenie tablic**

In [10]:
tabZeros = np.zeros(shape = [4, 10])
print(tabZeros)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [11]:
tabOnes = np.ones(shape = [5,5], dtype = 'int64')
print(tabOnes)
print(tabOnes.dtype)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
int64


In [13]:
tabFull = np.full(shape = [3,3], fill_value= 5)
print(tabFull)
print(tabFull.dtype)

[[5 5 5]
 [5 5 5]
 [5 5 5]]
int64


In [15]:
tabArange10 = np.arange(10)
print(tabArange10)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
tabArange5_9 = np.arange(start = 5, stop = 10)
print(tabArange5_9)

[5 6 7 8 9]


In [17]:
tabArange10_90 = np.arange(start = 10, stop = 91, step = 10)
print(tabArange10_90)

[10 20 30 40 50 60 70 80 90]


In [18]:
tabArange100_20 = np.arange(start = 100, stop = 10, step = -10)
print(tabArange100_20)

[100  90  80  70  60  50  40  30  20]


In [19]:
tabLinspace0_1 = np.linspace(start = 0, stop = 1, num=11)
print(tabLinspace0_1)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [26]:
A = np.arange(15)
print(A)
print()
B = A.reshape((3, 5))
print(B)
print()
C = A.reshape((5, -1))
print(C)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


**Podstawowe operacje na tablicach**